version: '3.8'

services:
  redis:
    container_name: python_redis
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: python_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cda

  python-app:
    container_name: python_latest
    build: .
    volumes:
      - ./src/:/usr/src/app
    depends_on:
      - redis
      - mongodb